language: ruby

sudo: false

rvm:
  - 2.3.1

services:
  - postgresql

script:
  - ./script/cibuild

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

env:
  - TEST_SUITE=rspec GITHUB_CLIENT_ID=client_id GITHUB_CLIENT_SECRET=client_secret WEBHOOK_SECRET=abcdefg
  - TEST_SUITE=linters

notifications:
  email: false
