language: ruby

sudo: false

rvm:
  - 2.3.1

script:
  - ./script/cibuild

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

env:
  - TEST_SUITE=rspec DB=postgresql GITHUB_CLIENT_ID=client_id GITHUB_CLIENT_SECRET=client_secret WEBHOOK_SECRET=abcdefg
  - TEST_SUITE=rubocop
  - TEST_SUITE=scss
  - TEST_SUITE=coffee

notifications:
  email: false
